/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hack_36_project;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.geom.AffineTransform;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.io.IOException;
import java.lang.ref.WeakReference;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Node;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.Document;
import org.icepdf.core.AnnotationCallback;
import org.icepdf.core.SecurityCallback;
import org.icepdf.core.pobjects.Page;
import org.icepdf.core.views.PageViewComponent;
import org.icepdf.core.views.swing.AbstractPageViewComponent;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.icepdf.ri.common.views.AbstractDocumentView;
import org.icepdf.ri.common.views.DocumentViewModelImpl;

/**
 *
 * @author asus
 */
public class Pdf_Viewer extends javax.swing.JFrame {
    private Node question;

    /**
     * Creates new form PDF_Viewer
     */
    public Pdf_Viewer() {
        
        System.getProperties().put("org.icepdf.core.views.background.color", "#FFFFFF");
        System.getProperties().put("org.icepdf.core.views.page.border.color", "#FFFFFF");
        System.getProperties().put("org.icepdf.core.views.page.shadow.color", "#FFFFFF");
        
        initComponents();
        A();
    }
    
    void A()
    {
        Thread th=new Thread(new Runnable() {

            @Override
            public void run() {
                
                while(true)
                {
                   
                        String ans=readClipboard();
                        System.out.println(ans);
                                
                }
            }
        });
        th.start();
    }
    
    public String readClipboard(){
        try {
            return (String) Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor);
        } catch (UnsupportedFlavorException ex) {
            Logger.getLogger(Pdf_Viewer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Pdf_Viewer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
}
    
   
    
   
        



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_open_pdf = new javax.swing.JButton();
        pdf_scroll_pane = new javax.swing.JScrollPane();
        AboveJPanel = new javax.swing.JPanel();
        search_video = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        BelowJPanel = new javax.swing.JPanel();
        search_dict = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1500, 1020));

        btn_open_pdf.setBackground(new java.awt.Color(255, 255, 255));
        btn_open_pdf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_open_pdf.setForeground(new java.awt.Color(255, 51, 0));
        btn_open_pdf.setText("Open Pdf");
        btn_open_pdf.setOpaque(false);
        btn_open_pdf.setRequestFocusEnabled(false);
        btn_open_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_open_pdfActionPerformed(evt);
            }
        });

        pdf_scroll_pane.setBackground(new java.awt.Color(255, 255, 255));
        pdf_scroll_pane.setAutoscrolls(true);
        pdf_scroll_pane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pdf_scroll_paneMouseReleased(evt);
            }
        });

        AboveJPanel.setBackground(new java.awt.Color(51, 51, 255));
        AboveJPanel.setForeground(new java.awt.Color(204, 255, 204));

        search_video.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_SEO_search_969259 (3).png"))); // NOI18N
        search_video.setBorder(null);
        search_video.setContentAreaFilled(false);
        search_video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_videoActionPerformed(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt3.setToolTipText("Search Here");
        txt3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt3KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout AboveJPanelLayout = new javax.swing.GroupLayout(AboveJPanel);
        AboveJPanel.setLayout(AboveJPanelLayout);
        AboveJPanelLayout.setHorizontalGroup(
            AboveJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboveJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_video, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AboveJPanelLayout.setVerticalGroup(
            AboveJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboveJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboveJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt3)
                    .addComponent(search_video, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        BelowJPanel.setBackground(new java.awt.Color(204, 255, 0));

        search_dict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/iconfinder_SEO_search_969259 (3).png"))); // NOI18N
        search_dict.setBorder(null);
        search_dict.setContentAreaFilled(false);
        search_dict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_dictActionPerformed(evt);
            }
        });

        txt2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt2.setToolTipText("Search Here");
        txt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout BelowJPanelLayout = new javax.swing.GroupLayout(BelowJPanel);
        BelowJPanel.setLayout(BelowJPanelLayout);
        BelowJPanelLayout.setHorizontalGroup(
            BelowJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BelowJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_dict, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BelowJPanelLayout.setVerticalGroup(
            BelowJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BelowJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BelowJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt2)
                    .addComponent(search_dict, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(434, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_open_pdf)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(pdf_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AboveJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BelowJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_open_pdf)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AboveJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BelowJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pdf_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2KeyTyped

    private void search_dictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_dictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_dictActionPerformed

    private void txt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3KeyTyped

    private void search_videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_videoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_videoActionPerformed

    private void pdf_scroll_paneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdf_scroll_paneMouseReleased

    }//GEN-LAST:event_pdf_scroll_paneMouseReleased

    private void btn_open_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_open_pdfActionPerformed
        // TODO add your handling code here:

        JFileChooser ch=new JFileChooser();
        ch.setFileFilter(new FileFilter(){

            @Override
            public boolean accept(File f) {
                String name = f.getName();
                return f.isDirectory() || name.endsWith(".pdf");
            }

            @Override
            public String getDescription() {
                return "pdf";
            }

        });
        int c=ch.showOpenDialog(this);
        if(c==JFileChooser.APPROVE_OPTION)
        {
            openpdf(ch.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_btn_open_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void openpdf(String file){
  
    try {
 
           SwingController control=new SwingController();
           
            SwingViewBuilder factry=new SwingViewBuilder(control);
            
            JPanel veiwerCompntpnl=factry.buildViewerPanel();
            ComponentKeyBinding.install(control, veiwerCompntpnl);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                    control.getDocumentViewController()));
                    control.openDocument(file);
            pdf_scroll_pane.setViewportView(veiwerCompntpnl); 
      } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Cannot Load Pdf");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdf_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdf_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdf_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdf_Viewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdf_Viewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboveJPanel;
    private javax.swing.JPanel BelowJPanel;
    private javax.swing.JButton btn_open_pdf;
    private javax.swing.JScrollPane pdf_scroll_pane;
    private javax.swing.JButton search_dict;
    private javax.swing.JButton search_video;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
